
-- banco postgres
CREATE DATABASE quarkus-social;

CREATE TABLE users (
                       id bigserial not null primary key,
                       name varchar(100) not null,
                       age integer not null
);

-- banco oracle

CREATE TABLE POSTS (
  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  texto VARCHAR2(150) NOT NULL,
  dateTime DATE, USER_ID NUMBER,
  PRIMARY KEY (ID), FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
